Chore/set request batch limit
VectorInstitute/kaleidoscope pull request #39
Opened 2023-03-22 14:58 UTC by xeon27

# PR Type ([Feature | Fix | Documentation | Test])
Fix

## Short Description
Return bad request if batch size of request exceeds BATCH_REQUEST_SIZE value set in config.

## Tests Added
...

2023-04-12 19:17 UTC, markcoatsworth commented on web/config.py
> +    BATCH_REQUEST_LIMIT = 8
For consistency, we should put this value in the `.env` file and then read it in like the other config values.

2023-04-12 20:02 UTC, markcoatsworth requested changes
Added one tiny request but otherwise looks good.

2023-04-13 18:54 UTC, xeon27 commented on web/config.py
> +    BATCH_REQUEST_LIMIT = 8
Made this change.

2023-04-13 21:04 UTC, markcoatsworth commented on web/config.py
> +    BATCH_REQUEST_LIMIT = 8
Great thanks!

2023-04-14 13:34 UTC, merged