Feature/kill unused models
VectorInstitute/kaleidoscope pull request #43
Opened 2023-03-31 03:21 UTC by jwilles

# PR Type ([Feature | Fix | Documentation | Test])

## Short Description
...

## Tests Added
...

2023-03-31 21:16 UTC, xeon27 requested changes

2023-03-31 21:16 UTC, xeon27 commented on web/models.py
> +            last_event_datetime = last_generation.created_at
Shouldn't this be:
```suggestion
            last_event_datetime = last_generation.updated_at
```
to reflect the time when the generation was completed?

2023-03-31 21:16 UTC, xeon27 commented on web/models.py
> +        last_generation_query = db.select(ModelInstanceGeneration).where(ModelInstanceGeneration.model_instance_id == self.id).order_by(ModelInstanceGeneration.created_at.desc())
If the above comment holds, this should also change to the following right?
```suggestion
        last_generation_query = db.select(ModelInstanceGeneration).where(ModelInstanceGeneration.model_instance_id == self.id).order_by(ModelInstanceGeneration.updated_at.desc())
```

2023-04-04 13:54 UTC, markcoatsworth commented on web/models.py
> +            last_event_datetime = last_generation.created_at
I'm pretty sure these values will be the same and so it doesn't matter?

2023-04-04 14:04 UTC, markcoatsworth commented on web/models.py
> +        return False
Do we not want to check for timeouts while the model is loading? If something gets stuck while loading (say we landed on a bad node) don't we eventually want to shut it down?

2023-04-04 14:32 UTC, markcoatsworth approved these changes
Couple minor comments but otherwise I think this looks good.

2023-04-04 15:52 UTC, jwilles commented on web/models.py
> +        return False
It's a great point but I think that is a different problem than what the timeout is solving - which is shutting down unused models. That functionality should likely be added to the health check instead.

2023-04-04 21:12 UTC, xeon27 commented on web/models.py
> +            last_event_datetime = last_generation.created_at
Ohh, I thought `created_at` is creation time of generation request object and `updated_at` is when the `generation` attribute is assigned, making them different based on generation time.

2023-04-17 16:22 UTC, merged