Feature/production server
VectorInstitute/kaleidoscope pull request #46
Opened 2023-04-16 22:42 UTC by janakan2466

# PR Type (Feature)

## Short Description
This PR contains the following implementations:
- Addition of reverse proxy: Nginx
- Addition of web server: Gunicorn

## Tests Added
End-to-end testing were done on staging environments.

2023-04-24 16:16 UTC, markcoatsworth commented on web/Dockerfile
> +# CMD ["gunicorn", "--config", "gunicorn.conf.py"]
We don't need to keep the old gateway_service call in here. Just rip it out and replace it with gunicorn. We don't want or need two separate ways to start it, gunicorn should be the only way.

2023-04-24 16:17 UTC, markcoatsworth commented on web/docker-compose-prod.yaml
> +    name: kaleidoscope-staging_postgres_data_staging
As with the above comment, we don't want a separate compose file for the gunicorn deployment. Moving forward that's going to be our only deployment. So please remove this separate file and incorporate the changes back into `docker-compose-staging.yaml` and `docker-compose.yaml`

2023-04-24 16:18 UTC, markcoatsworth commented on web/migrations/versions/0acbe22f9b73_.py
> +    # ### end Alembic commands ###
I don't think anything was changed here? If not then please just leave the file untouched

2023-04-24 16:19 UTC, markcoatsworth commented on web/requirements.txt
> +zipp==3.15.0
Why were all these dependencies re-added? I don't think we use any of them and they add a lot of bloat to our container. Unless we specifically need them, don't add them.

2023-04-24 16:22 UTC, markcoatsworth commented on web/nginx/Dockerfile
> +COPY nginx.conf /etc/nginx/conf.d
Is there a reason for deploying the nginx app into a separate container? Unless we specifically need it to live apart from the gateway_service/gunicorn container, it would be cleaner to just have everything all in the same one.

2023-04-24 16:24 UTC, markcoatsworth requested changes
I just added a bunch of comments. The biggest issue is we don't want gunicorn/nginx to exist as a separate deployment from the old gateway_service; we want to fully replace and remove the old one. Take a look and let me know.

2023-04-25 17:31 UTC, jwilles commented on web/nginx/Dockerfile
> +COPY nginx.conf /etc/nginx/conf.d
A good rule of thumb is one process per container. See [here](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container) for more in depth discussion. Best practice is generally to run the reverse proxy in a separate container so no issues with this from my side.

2023-04-25 17:32 UTC, jwilles commented on web/gateway_service.py
> +    # app.celery = celery
Why is this removed?

2023-04-26 23:48 UTC, janakan2466 commented on web/requirements.txt
> +zipp==3.15.0
A couple of notes:
- My though process: there are some PIP packages without specified versions, ultimately this file would be able to replicate a functional instance of our service at this point in time. (ex. if `flask-jwt-extended` received a new update which was not functional with `flask-ldap3-login` then we would have some dependancy issues)
- Some of these packages are composed of other libraries so they are automatically downloaded, regardless if someone where to run our environment they will have to end up downloading the same packages

2023-04-28 15:00 UTC, markcoatsworth commented
I'm still not sure about commenting out celery, but otherwise this looks good. I'm going to merge it and deploy on staging, we can deal with any outstanding issues later.

2023-04-28 15:00 UTC, merged