Release/0.9.0
VectorInstitute/kaleidoscope pull request #68
Opened 2023-08-22 16:56 UTC by markcoatsworth

# PR Type (Release)

## Short Description
* Added llama2 model
* Removed older llama model
* Fixed issue with multi-prompt generation for opt

2023-08-22 18:17 UTC, jwilles commented on model_service/models/llama2/launch_llama2-13b.slurm
>  #SBATCH --mem=0
Why do we have mem set to 0 here?

2023-08-22 18:18 UTC, jwilles commented on model_service/models/llama2/launch_llama2-70b.slurm
> +#SBATCH --mem=0
Why is mem set to 0?

2023-08-22 19:07 UTC, xeon27 requested changes
Added a few comments.

2023-08-22 19:07 UTC, xeon27 commented on model_service/models/llama2/model.py
> +        generated_sequences = GENERATOR.tokenizer.decode(results["choices"][0]["text"][0])
```suggestion
        generated_sequences = GENERATOR.tokenizer.decode(results["choices"][0]["text"])
```
Why are we only extracting the first generated sequence? `len(tokens) == len(generated_sequences)` should hold right? Am I missing any logic here?

2023-08-22 19:43 UTC, markcoatsworth commented on model_service/models/llama2/launch_llama2-13b.slurm
>  #SBATCH --mem=0
Setting `--mem=0` requests all the memory on a node

2023-08-22 19:43 UTC, markcoatsworth commented on model_service/models/llama2/launch_llama2-70b.slurm
> +#SBATCH --mem=0
As above, `--mem=0` requests all memory on a node

2023-08-22 19:46 UTC, markcoatsworth commented on model_service/models/llama2/launch_llama2-7b.slurm
> +model_path="/ssd005/projects/llm/Llama-2-7b-chat"
I used the chat version here because this was the only version we had in the correct .pth weights. We can easily change this, but would need to download the non-chat weights, I think we can just change this later.

2023-08-22 20:26 UTC, markcoatsworth commented on model_service/models/llama2/hosting_utils.py
> +    logprobs: List[float]
No, there's only a single logprob value for each token. If you make a request with multiple prompts, we get a separate ResponseObject for each one.

2023-08-22 20:28 UTC, markcoatsworth commented on model_service/models/llama2/model.py
> +        generated_sequences = GENERATOR.tokenizer.decode(results["choices"][0]["text"][0])
That's just because all the sequences are wrapped in a list object under the hood. I don't know why Meta did it that way. If there are multiple generated sequences, that `[0]` element contains a list of all sequences.

2023-08-22 21:02 UTC, xeon27 commented on model_service/models/llama2/hosting_utils.py
> +    logprobs: List[float]
Understood, I mistook generations to be a list of generations for different prompts.

2023-08-22 21:07 UTC, markcoatsworth commented on model_service/models/llama2/launch_llama2-7b.slurm
> +model_path="/ssd005/projects/llm/Llama-2-7b-chat"
... barely a minute after you posted this, Matt put the non-chat weights for all three models into a new common folder on the cluster. I've updated the .slurm files to point to this folder.

2023-08-22 21:08 UTC, xeon27 requested changes

2023-08-22 21:08 UTC, xeon27 commented on model_service/models/llama2/model.py
> +        for sequence in results["choices"][0]["text"]:
```suggestion
        for sequence in results["choices"][0]["text"][0]:
```
Based on https://github.com/VectorInstitute/kaleidoscope/pull/68/files#r1302074740, `[0]` should be added here as well right?

2023-08-23 12:33 UTC, markcoatsworth commented on model_service/models/llama2/model.py
> +        for sequence in results["choices"][0]["text"]:
Nice catch! It turns out the response generation changed after we fixed a different bug, and the `[0]` should not have been here in the first place. I've removed it.

2023-08-24 17:13 UTC, markcoatsworth commented
We chatted about this in person and ready to merge + release, LGTM

2023-08-24 17:13 UTC, merged