Release/0.10.0
VectorInstitute/kaleidoscope pull request #77
Opened 2023-10-13 14:59 UTC by markcoatsworth

# PR Type ([Release])

## Short Description
* Fixed generation bug in Llama2
* Removed batching loop from Llama2 code, all batching is now handled by Triton
* Added missing config parameter to env-example
* Fixed Llama2 module layer names
* Set Docker restart policy to always

2023-10-13 20:13 UTC, xeon27 requested changes

2023-10-13 20:13 UTC, xeon27 commented on model_service/models/llama2/config.json
>  	"module_names":
Module names should be based on model variants right? Since different sizes have different number of layers.

2023-10-13 20:44 UTC, jwilles commented on model_service/models/llama2/config.json
>  	"module_names":
+1

2023-10-13 20:46 UTC, jwilles commented on model_service/models/llama2/config.json
>  	"module_names":
We also need to add a "-chat" modifier to these variant names. My understanding is that they are all the chat variant right?

2023-10-17 14:50 UTC, xeon27 approved these changes

2023-10-17 14:52 UTC, xeon27 approved these changes
Module names for different model variants and adding the chat modifier will be handled in the next release.

2023-10-18 16:12 UTC, jwilles approved these changes

2023-10-18 16:26 UTC, merged